-- MySQL Script generated by MySQL Workbench
-- Thu Sep  3 23:05:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_sistemaCgae
-- -----------------------------------------------------
-- Banco de dados criado para o sistema de atendimento do Cgae utilizando o a linguagem JAVA por José Neto Lima Nascimento
DROP SCHEMA IF EXISTS `db_sistemaCgae` ;

-- -----------------------------------------------------
-- Schema db_sistemaCgae
--
-- Banco de dados criado para o sistema de atendimento do Cgae utilizando o a linguagem JAVA por José Neto Lima Nascimento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sistemaCgae` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
SHOW WARNINGS;
USE `db_sistemaCgae` ;

-- -----------------------------------------------------
-- Table `tb_publico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_publico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_publico` (
)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
